### ISSUE TITLE
subscribers are deleted when staging site is pushed to live

### ISSUE THREAD

**Issue by Rik44444** [mailpoet/mailpoet#3002] opened 2020-08-26 10:20 UTC
Dear Mailpoet,
I use the kind of amazing feature of Wordpress to have a staging site, where we can test various updates to the site, that we then push to live once every so often. See here: https://www.wpbeginner.com/wp-tutorials/how-to-create-staging-environment-for-a-wordpress-site/
i just noticed that when we push the site to live, anyone who has subscribed via our 'real' site is deleted from the Mailpoet database. Do you have a solution for this?
Rik
site: https://future.ngo
staging site: https://testtest.future.ngo

**Comment by costasovo** [comment] 2020-09-08 15:09
Hi @Rik44444,
Based on your description it seems that script which promotes the staging site to production overwrites MailPoet DB tables by data from staging. 
Is it possible to skip some tables before you push to production? I mean all tables starting with wp_mailpoet_... (where wp_ vary by the DB refix you set in wp-config.php)
MailPoet plugin should recognize that the production DB structure is outdated and is able to update tables itself.

**Comment by Rik44444** [comment] 2020-09-29 12:26
you are right, when i exclude the mailpoet tables, new mailpoet subscribers are preserved in the installation. It would be good if this could somehow be made the default: perhaps you could connect with Softalicious to ask that mailpoet tables are 'unchecked' by default when a site is pushed to live?

**Comment by pavel-mailpoet** [comment] 2020-09-29 12:33
Thanks for the update @Rik44444 since the problem is not with MailPoet plugin I will close this issue.

**Closed by pavel-mailpoet** 2020-09-29 12:33 UTC

**Comment by Rik44444** [comment] 2020-09-29 13:07
hi @pavel-mailpoet , i mildly disagree with your closing :) how about this request, this is definitely about your plugin:

perhaps you could connect with Softalicious to ask that mailpoet tables are 'unchecked' by default when a site is pushed to live?

**Comment by NeosinneR** [comment] 2020-09-30 08:40
Hey @Rik44444, we are a rather small team and we don't have the capacity to implement or comply with all requests by our users. What I can do, is direct you to https://feedback.mailpoet.com/integrations where you can create a request for better integration with Softalicious and if there are more customers with the same problem, we might look into it in the future.

**Comment by AnneMerrill** [comment] 2022-02-25 15:03
So if I want to use Softalicious would I be better off going with Mailchimp?

**Comment by costasovo** [comment] 2022-03-01 08:19
@AnneMerrill If I'm not mistaken (see [this comment](https://github.com/mailpoet/mailpoet/issues/3002#issuecomment-700668034)), you can work around the issue with staging overwriting production by excluding mailpoet tables (all DB tables that contains _mailpoet_).

**Comment by AnneMerrill** [comment] 2022-03-01 09:11
Ok, yeah, that's not a level I feel confident messing around at.
