### ISSUE TITLE
Cannot translate Woocommerce checkbox opt-in message string in WPML

### ISSUE THREAD

**Issue by poehaldur** [mailpoet/mailpoet#3129] opened 2020-10-25 20:03 UTC
In the file /wp-content/plugins/mailpoet/lib/WooCommerce/Subscription.php on line 59 is the following code:
Can this be made into snippet as a functions.php to overwrite the plugin label? 

`  private function getSubscriptionField($inputName, $checked, $labelString) {
    return '<p class="form-row">
      <label class="woocommerce-form__label woocommerce-form__label-for-checkbox checkbox" data-automation-id="woo-commerce-subscription-opt-in">
      <input type="checkbox" class="woocommerce-form__input woocommerce-form__input-checkbox input-checkbox" name="' . $this->wp->escAttr($inputName) . '" id="' . $this->wp->escAttr($inputName) . '" ' . ($checked ? 'checked' : '') . ' />
        <span class="woocommerce-terms-and-conditions-checkbox-text">' . $this->wp->escHtml($labelString) . '</label>
    </p>';
  }`

It seems to be a common problem in WPML ([https://wpml.org/forums/topic/cannot-translate-mailpoet-string/](https://wpml.org/forums/topic/cannot-translate-mailpoet-string/)) 
Really need to have it fixed, as it cannot be used on translated websites in checkout.

**Comment by NeosinneR** [comment] 2020-10-26 08:12
Hi @poehaldur, we are aware of this issue and are tracking it also in our internal system. I don't have any specific timeframe when it'll be fixed, but we'll let you know once it's done. 

Duplicate of #2795

**Closed by NeosinneR** 2020-10-26 08:12 UTC

**Comment by lysyjan** [comment] 2021-01-07 13:27
Hi @poehaldur,
your issue is fixed in our latest version.

Thanks again for reporting the issue!
